# Generated by Django 5.2.8 on 2025-11-20 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_moisture',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_ph',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_temp',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_light',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_temperature',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_humidity',
            field=models.CharField(max_length=50),
        ),
    ]
