# Generated by Django 5.2.8 on 2025-11-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_sensordata_remove_plant_ideal_moisture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_humidity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_light',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_temperature',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_humidity_max',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_humidity_min',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_moisture_max',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_moisture_min',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_temp_max',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_temp_min',
            field=models.IntegerField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(),
        ),
    ]
