# Generated by Django 5.2.8 on 2025-11-21 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sensordata_remove_plant_ideal_humidity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='plant',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='api.plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_humidity_max',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_humidity_min',
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_moisture_max',
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_moisture_min',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_temp_max',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_temp_min',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
