# Generated by Django 5.2.8 on 2025-11-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensordata_plant_sensordata_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='plant',
        ),
    ]
